### ISSUE TITLE
Duplicate Setting Malfunction

### ISSUE THREAD

**Issue by ItzEdInYourBed** [WilDev-Studios/Wild.Announcer#1]
Hello,

It appears that "Prevent-Duplicates:" is not working correctly.
https://i.imgur.com/4ghHtWU.png
https://pastebin.com/BW9H8L0B

**Comment by WildKadeGaming** [comment]
Hi ItszEdInYourBed,

If you could join our Discord and discuss this in more detail that would be great :)

Thanks,
- Wild
